List<Map<String, String>> country = [
  {'code': 'AD', 'name': 'Andorra', 'p_code': '+376'},
  {'code': 'AE', 'name': 'United Arab Emirates', 'p_code': '+971'},
  {'code': 'AF', 'name': 'Afghanistan', 'p_code': '+93'},
  {'code': 'AG', 'name': 'Antigua and Barbuda', 'p_code': '+1'},
  {'code': 'AI', 'name': 'Anguilla', 'p_code': '+1'},
  {'code': 'AL', 'name': 'Albania', 'p_code': '+355'},
  {'code': 'AM', 'name': 'Armenia', 'p_code': '+374'},
  {'code': 'AN', 'name': 'Netherlands Antilles', 'p_code': '+599'},
  {'code': 'AO', 'name': 'Angola', 'p_code': '+244'},
  {'code': 'AR', 'name': 'Argentina', 'p_code': '+54'},
  {'code': 'AS', 'name': 'American Samoa', 'p_code': '+1'},
  {'code': 'AT', 'name': 'Austria', 'p_code': '+43'},
  {'code': 'AU', 'name': 'Australia', 'p_code': '+61'},
  {'code': 'AW', 'name': 'Aruba', 'p_code': '+297'},
  {'code': 'AZ', 'name': 'Azerbaijan', 'p_code': '+994'},
  {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'p_code': '+387'},
  {'code': 'BB', 'name': 'Barbados', 'p_code': '+1'},
  {'code': 'BD', 'name': 'Bangladesh', 'p_code': '+880'},
  {'code': 'BE', 'name': 'Belgium', 'p_code': '+32'},
  {'code': 'BF', 'name': 'Burkina Faso', 'p_code': '+226'},
  {'code': 'BG', 'name': 'Bulgaria', 'p_code': '+359'},
  {'code': 'BH', 'name': 'Bahrain', 'p_code': '+973'},
  {'code': 'BI', 'name': 'Burundi', 'p_code': '+257'},
  {'code': 'BJ', 'name': 'Benin', 'p_code': '+229'},
  {'code': 'BL', 'name': 'Saint Barthelemy', 'p_code': '+590'},
  {'code': 'BM', 'name': 'Bermuda', 'p_code': '+1'},
  {'code': 'BN', 'name': 'Brunei', 'p_code': '+673'},
  {'code': 'BO', 'name': 'Bolivia', 'p_code': '+591'},
  {'code': 'BR', 'name': 'Brazil', 'p_code': '+55'},
  {'code': 'BS', 'name': 'Bahamas', 'p_code': '+1'},
  {'code': 'BT', 'name': 'Bhutan', 'p_code': '+975'},
  {'code': 'BW', 'name': 'Botswana', 'p_code': '+267'},
  {'code': 'BY', 'name': 'Belarus', 'p_code': '+375'},
  {'code': 'BZ', 'name': 'Belize', 'p_code': '+501'},
  {'code': 'CA', 'name': 'Canada', 'p_code': '+1'},
  {'code': 'CC', 'name': 'Cocos Islands', 'p_code': '+61'},
  {'code': 'CD', 'name': 'Democratic Republic of the Congo', 'p_code': '+243'},
  {'code': 'CF', 'name': 'Central African Republic', 'p_code': '+236'},
  {'code': 'CG', 'name': 'Republic of the Congo', 'p_code': '+242'},
  {'code': 'CH', 'name': 'Switzerland', 'p_code': '+41'},
  {'code': 'CI', 'name': 'Ivory Coast', 'p_code': '+225'},
  {'code': 'CK', 'name': 'Cook Islands', 'p_code': '+682'},
  {'code': 'CL', 'name': 'Chile', 'p_code': '+56'},
  {'code': 'CM', 'name': 'Cameroon', 'p_code': '+237'},
  {'code': 'CN', 'name': 'China', 'p_code': '+86'},
  {'code': 'CO', 'name': 'Colombia', 'p_code': '+57'},
  {'code': 'CR', 'name': 'Costa Rica', 'p_code': '+506'},
  {'code': 'CU', 'name': 'Cuba', 'p_code': '+53'},
  {'code': 'CV', 'name': 'Cape Verde', 'p_code': '+238'},
  {'code': 'CX', 'name': 'Christmas Island', 'p_code': '+61'},
  {'code': 'CY', 'name': 'Cyprus', 'p_code': '+537'},
  {'code': 'CZ', 'name': 'Czech Republic', 'p_code': '+420'},
  {'code': 'DE', 'name': 'Germany', 'p_code': '+49'},
  {'code': 'DJ', 'name': 'Djibouti', 'p_code': '+253'},
  {'code': 'DK', 'name': 'Denmark', 'p_code': '+45'},
  {'code': 'DM', 'name': 'Dominica', 'p_code': '+1'},
  {'code': 'DO', 'name': 'Dominican Republic', 'p_code': '+1'},
  {'code': 'DZ', 'name': 'Algeria', 'p_code': '+213'},
  {'code': 'EC', 'name': 'Ecuador', 'p_code': '+593'},
  {'code': 'EE', 'name': 'Estonia', 'p_code': '+372'},
  {'code': 'EG', 'name': 'Egypt', 'p_code': '+20'},
  {'code': 'ER', 'name': 'Eritrea', 'p_code': '+291'},
  {'code': 'ES', 'name': 'Spain', 'p_code': '+34'},
  {'code': 'ET', 'name': 'Ethiopia', 'p_code': '+251'},
  {'code': 'FI', 'name': 'Finland', 'p_code': '+358'},
  {'code': 'FJ', 'name': 'Fiji', 'p_code': '+679'},
  {'code': 'FK', 'name': 'Falkland Islands', 'p_code': '+500'},
  {'code': 'FM', 'name': 'Micronesia', 'p_code': '+691'},
  {'code': 'FO', 'name': 'Faroe Islands', 'p_code': '+298'},
  {'code': 'FR', 'name': 'France', 'p_code': '+33'},
  {'code': 'GA', 'name': 'Gabon', 'p_code': '+241'},
  {'code': 'GB', 'name': 'United Kingdom', 'p_code': '+44'},
  {'code': 'GD', 'name': 'Grenada', 'p_code': '+1'},
  {'code': 'GE', 'name': 'Georgia', 'p_code': '+995'},
  {'code': 'GF', 'name': 'French Guiana', 'p_code': '+594'},
  {'code': 'GG', 'name': 'Guernsey', 'p_code': '+44'},
  {'code': 'GH', 'name': 'Ghana', 'p_code': '+233'},
  {'code': 'GI', 'name': 'Gibraltar', 'p_code': '+350'},
  {'code': 'GL', 'name': 'Greenland', 'p_code': '+299'},
  {'code': 'GM', 'name': 'Gambia', 'p_code': '+220'},
  {'code': 'GN', 'name': 'Guinea', 'p_code': '+224'},
  {'code': 'GP', 'name': 'Guadeloupe', 'p_code': '+590'},
  {'code': 'GQ', 'name': 'Equatorial Guinea', 'p_code': '+240'},
  {'code': 'GR', 'name': 'Greece', 'p_code': '+30'},
  {
    'code': 'GS',
    'name': 'South Georgia and the South Sandwich Islands',
    'p_code': '+500'
  },
  {'code': 'GT', 'name': 'Guatemala', 'p_code': '+502'},
  {'code': 'GU', 'name': 'Guam', 'p_code': '+1'},
  {'code': 'GW', 'name': 'Guinea-Bissau', 'p_code': '+245'},
  {'code': 'GY', 'name': 'Guyana', 'p_code': '+595'},
  {'code': 'HK', 'name': 'Hong Kong', 'p_code': '+852'},
  {'code': 'HN', 'name': 'Honduras', 'p_code': '+504'},
  {'code': 'HR', 'name': 'Croatia', 'p_code': '+385'},
  {'code': 'HT', 'name': 'Haiti', 'p_code': '+509'},
  {'code': 'HU', 'name': 'Hungary', 'p_code': '+36'},
  {'code': 'IE', 'name': 'Ireland', 'p_code': '+353'},
  {'code': 'IL', 'name': 'Israel', 'p_code': '+972'},
  {'code': 'IM', 'name': 'Isle of Man', 'p_code': '+44'},
  {'code': 'IN', 'name': 'India', 'p_code': '+91'},
  {'code': 'IO', 'name': 'British Indian Ocean Territory', 'p_code': '+246'},
  {'code': 'IQ', 'name': 'Iraq', 'p_code': '+964'},
  {'code': 'IR', 'name': 'Iran', 'p_code': '+98'},
  {'code': 'IS', 'name': 'Iceland', 'p_code': '+354'},
  {'code': 'IT', 'name': 'Italy', 'p_code': '+39'},
  {'code': 'JE', 'name': 'Jersey', 'p_code': '+44'},
  {'code': 'JM', 'name': 'Jamaica', 'p_code': '+1'},
  {'code': 'JO', 'name': 'Jordan', 'p_code': '+962'},
  {'code': 'JP', 'name': 'Japan', 'p_code': '+81'},
  {'code': 'KE', 'name': 'Kenya', 'p_code': '+254'},
  {'code': 'KG', 'name': 'Kyrgyzstan', 'p_code': '+996'},
  {'code': 'KH', 'name': 'Cambodia', 'p_code': '+855'},
  {'code': 'KI', 'name': 'Kiribati', 'p_code': '+686'},
  {'code': 'KM', 'name': 'Comoros', 'p_code': '+62'},
  {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'p_code': '+1'},
  {'code': 'KP', 'name': 'North Korea', 'p_code': '+850'},
  {'code': 'KR', 'name': 'South Korea', 'p_code': '+82'},
  {'code': 'KW', 'name': 'Kuwait', 'p_code': '+965'},
  {'code': 'KY', 'name': 'Cayman Islands', 'p_code': '+345'},
  {'code': 'KZ', 'name': 'Kazakhstan', 'p_code': '+77'},
  {'code': 'LA', 'name': 'Laos', 'p_code': '+856'},
  {'code': 'LB', 'name': 'Lebanon', 'p_code': '+961'},
  {'code': 'LC', 'name': 'Saint Lucia', 'p_code': '+1'},
  {'code': 'LI', 'name': 'Liechtenstein', 'p_code': '+423'},
  {'code': 'LK', 'name': 'Sri Lanka', 'p_code': '+94'},
  {'code': 'LR', 'name': 'Liberia', 'p_code': '+231'},
  {'code': 'LS', 'name': 'Lesotho', 'p_code': '+266'},
  {'code': 'LT', 'name': 'Lithuania', 'p_code': '+370'},
  {'code': 'LU', 'name': 'Luxembourg', 'p_code': '+352'},
  {'code': 'LV', 'name': 'Latvia', 'p_code': '+371'},
  {'code': 'LY', 'name': 'Libya', 'p_code': '+218'},
  {'code': 'MA', 'name': 'Morocco', 'p_code': '+212'},
  {'code': 'MC', 'name': 'Monaco', 'p_code': '+377'},
  {'code': 'MD', 'name': 'Moldova', 'p_code': '+373'},
  {'code': 'ME', 'name': 'Montenegro', 'p_code': '+382'},
  {'code': 'MF', 'name': 'Saint Martin', 'p_code': '+590'},
  {'code': 'MG', 'name': 'Madagascar', 'p_code': '+261'},
  {'code': 'MH', 'name': 'Marshall Islands', 'p_code': '+692'},
  {'code': 'MK', 'name': 'Macedonia', 'p_code': '+389'},
  {'code': 'ML', 'name': 'Mali', 'p_code': '+223'},
  {'code': 'MM', 'name': 'Myanmar', 'p_code': '+95'},
  {'code': 'MN', 'name': 'Mongolia', 'p_code': '+976'},
  {'code': 'MO', 'name': 'Macao', 'p_code': '+853'},
  {'code': 'MP', 'name': 'Northern Mariana Islands', 'p_code': '+1'},
  {'code': 'MQ', 'name': 'Martinique', 'p_code': '+596'},
  {'code': 'MR', 'name': 'Mauritania', 'p_code': '+222'},
  {'code': 'MS', 'name': 'Montserrat', 'p_code': '+1'},
  {'code': 'MT', 'name': 'Malta', 'p_code': '+356'},
  {'code': 'MU', 'name': 'Mauritius', 'p_code': '+230'},
  {'code': 'MV', 'name': 'Maldives', 'p_code': '+960'},
  {'code': 'MW', 'name': 'Malawi', 'p_code': '+265'},
  {'code': 'MX', 'name': 'Mexico', 'p_code': '+52'},
  {'code': 'MY', 'name': 'Malaysia', 'p_code': '+60'},
  {'code': 'MZ', 'name': 'Mozambique', 'p_code': '+258'},
  {'code': 'NA', 'name': 'Namibia', 'p_code': '+264'},
  {'code': 'NC', 'name': 'New Caledonia', 'p_code': '+687'},
  {'code': 'NE', 'name': 'Niger', 'p_code': '+227'},
  {'code': 'NF', 'name': 'Norfolk Island', 'p_code': '+672'},
  {'code': 'NG', 'name': 'Nigeria', 'p_code': '+234'},
  {'code': 'NI', 'name': 'Nicaragua', 'p_code': '+505'},
  {'code': 'NL', 'name': 'Netherlands', 'p_code': '+31'},
  {'code': 'NO', 'name': 'Norway', 'p_code': '+47'},
  {'code': 'NP', 'name': 'Nepal', 'p_code': '+977'},
  {'code': 'NR', 'name': 'Nauru', 'p_code': '+674'},
  {'code': 'NU', 'name': 'Niue', 'p_code': '+683'},
  {'code': 'NZ', 'name': 'New Zealand', 'p_code': '+64'},
  {'code': 'OM', 'name': 'Oman', 'p_code': '+968'},
  {'code': 'PA', 'name': 'Panama', 'p_code': '+507'},
  {'code': 'PE', 'name': 'Peru', 'p_code': '+51'},
  {'code': 'PF', 'name': 'French Polynesia', 'p_code': '+689'},
  {'code': 'PG', 'name': 'Papua New Guinea', 'p_code': '+675'},
  {'code': 'PH', 'name': 'Philippines', 'p_code': '+63'},
  {'code': 'PK', 'name': 'Pakistan', 'p_code': '+92'},
  {'code': 'PL', 'name': 'Poland', 'p_code': '+48'},
  {'code': 'PM', 'name': 'Saint Pierre and Miquelon', 'p_code': '+508'},
  {'code': 'PN', 'name': 'Pitcairn', 'p_code': '+872'},
  {'code': 'PR', 'name': 'Puerto Rico', 'p_code': '+1'},
  {'code': 'PS', 'name': 'Palestinian Territory', 'p_code': '+970'},
  {'code': 'PT', 'name': 'Portugal', 'p_code': '+351'},
  {'code': 'PW', 'name': 'Palau', 'p_code': '+680'},
  {'code': 'PY', 'name': 'Paraguay', 'p_code': '+595'},
  {'code': 'QA', 'name': 'Qatar', 'p_code': '+974'},
  {'code': 'RE', 'name': 'Reunion', 'p_code': '+262'},
  {'code': 'RO', 'name': 'Romania', 'p_code': '+40'},
  {'code': 'RS', 'name': 'Serbia', 'p_code': '+381'},
  {'code': 'RU', 'name': 'Russia', 'p_code': '+7'},
  {'code': 'RW', 'name': 'Rwanda', 'p_code': '+250'},
  {'code': 'SA', 'name': 'Saudi Arabia', 'p_code': '+966'},
  {'code': 'SB', 'name': 'Solomon Islands', 'p_code': '+677'},
  {'code': 'SC', 'name': 'Seychelles', 'p_code': '+248'},
  {'code': 'SD', 'name': 'Sudan', 'p_code': '+249'},
  {'code': 'SE', 'name': 'Sweden', 'p_code': '+46'},
  {'code': 'SG', 'name': 'Singapore', 'p_code': '+65'},
  {'code': 'SH', 'name': 'Saint Helena', 'p_code': '+290'},
  {'code': 'SI', 'name': 'Slovenia', 'p_code': '+386'},
  {'code': 'SJ', 'name': 'Svalbard and Jan Mayen', 'p_code': '+47'},
  {'code': 'SK', 'name': 'Slovakia', 'p_code': '+421'},
  {'code': 'SL', 'name': 'Sierra Leone', 'p_code': '+232'},
  {'code': 'SM', 'name': 'San Marino', 'p_code': '+378'},
  {'code': 'SN', 'name': 'Senegal', 'p_code': '+221'},
  {'code': 'SO', 'name': 'Somalia', 'p_code': '+252'},
  {'code': 'SR', 'name': 'Suriname', 'p_code': '+597'},
  {'code': 'ST', 'name': 'Sao Tome and Principe', 'p_code': '+239'},
  {'code': 'SV', 'name': 'El Salvador', 'p_code': '+503'},
  {'code': 'SY', 'name': 'Syria', 'p_code': '+963'},
  {'code': 'SZ', 'name': 'Swaziland', 'p_code': '+268'},
  {'code': 'TC', 'name': 'Turks and Caicos Islands', 'p_code': '+1'},
  {'code': 'TD', 'name': 'Chad', 'p_code': '+235'},
  {'code': 'TG', 'name': 'Togo', 'p_code': '+228'},
  {'code': 'TH', 'name': 'Thailand', 'p_code': '+66'},
  {'code': 'TJ', 'name': 'Tajikistan', 'p_code': '+992'},
  {'code': 'TK', 'name': 'Tokelau', 'p_code': '+690'},
  {'code': 'TL', 'name': 'East Timor', 'p_code': '+670'},
  {'code': 'TM', 'name': 'Turkmenistan', 'p_code': '+993'},
  {'code': 'TN', 'name': 'Tunisia', 'p_code': '+216'},
  {'code': 'TO', 'name': 'Tonga', 'p_code': '+676'},
  {'code': 'TR', 'name': 'Turkey', 'p_code': '+90'},
  {'code': 'TT', 'name': 'Trinidad and Tobago', 'p_code': '+1'},
  {'code': 'TV', 'name': 'Tuvalu', 'p_code': '+688'},
  {'code': 'TW', 'name': 'Taiwan', 'p_code': '+886'},
  {'code': 'TZ', 'name': 'Tanzania', 'p_code': '+255'},
  {'code': 'UA', 'name': 'Ukraine', 'p_code': '+380'},
  {'code': 'UG', 'name': 'Uganda', 'p_code': '+256'},
  {'code': 'US', 'name': 'United States', 'p_code': '+1'},
  {'code': 'UY', 'name': 'Uruguay', 'p_code': '+598'},
  {'code': 'UZ', 'name': 'Uzbekistan', 'p_code': '+998'},
  {'code': 'VA', 'name': 'Vatican', 'p_code': '+379'},
  {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'p_code': '+1'},
  {'code': 'VE', 'name': 'Venezuela', 'p_code': '+58'},
  {'code': 'VG', 'name': 'British Virgin Islands', 'p_code': '+284'},
  {'code': 'VI', 'name': 'U.S. Virgin Islands', 'p_code': '+340'},
  {'code': 'VN', 'name': 'Vietnam', 'p_code': '+84'},
  {'code': 'VU', 'name': 'Vanuatu', 'p_code': '+678'},
  {'code': 'WF', 'name': 'Wallis and Futuna', 'p_code': '+681'},
  {'code': 'WS', 'name': 'Samoa', 'p_code': '+685'},
  {'code': 'YE', 'name': 'Yemen', 'p_code': '+967'},
  {'code': 'YT', 'name': 'Mayotte', 'p_code': '+262'},
  {'code': 'ZA', 'name': 'South Africa', 'p_code': '+27'},
  {'code': 'ZM', 'name': 'Zambia', 'p_code': '+260'},
  {'code': 'ZW', 'name': 'Zimbabwe', 'p_code': '+263'}
];
