name: chatnest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    firebase_auth: ^1.0.0
    cloud_firestore: ^1.0.0
    firebase_core: ^1.0.0
    flutter_svg: ^0.19.3
    shared_preferences: ^2.0.5
    pinput: ^1.2.0
    flutter_launcher_icons:
    page_transition: ^1.1.7+6
    lottie: ^0.7.0+1
    circular_countdown: ^2.0.0
    circular_countdown_timer: ^0.2.0
    image_picker: ^0.7.4
    http: ^0.13.2
    google_nav_bar: ^5.0.5
    line_icons: ^2.0.0
    ionicons: ^0.1.2
    curved_navigation_bar: ^0.3.7
    fab_circular_menu: ^1.0.0
    adobe_xd: ^1.1.0+1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/images/ChatNest.png"
    image_path_android: "assets/images/ChatNest.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/fonts/
        - assets/images/
        - assets/svgs/
        - assets/
        - assets/Animation/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto/Roboto-Regular.ttf

        - family: Roboto_Thin
          fonts:
              - asset: assets/fonts/Roboto/Roboto-Thin.ttf

        - family: OpenSans
          fonts:
              - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

        - family: OpenSans_Light
          fonts:
              - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
    
        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf

        - family: Ubuntu
          fonts:
              - asset: assets/fonts/Ubuntu-Regular.ttf

        - family: OdibeeSans
          fonts:
              - asset: assets/fonts/OdibeeSans-Regular.ttf

        # - family: 
        #   fonts:
        #       - asset: 

        # - family: 
        #   fonts:
        #       - asset: 

        # - family: 
        #   fonts:
        #       - asset: 'assets/fonts/'
    

    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
